# Generated by Django 3.2.12 on 2022-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chat_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='room_name',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='text_value',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
