version: '3.8'
services:
  pg_db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_NAME=newdb
        - POSTGRES_USER=newuser
        - POSTGRES_PASSWORD='1'
      ports:
        - ${POSTGRES_PORT:-5433}:5432
  web:
       build: .
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
           - .:/code
       ports:
           - "8000:8000"
       environment:
           - SECRET_KEY='django-insecure-pg+h99q6^$aksy$mtmdmz3)keh3t^+-r_lkta478^_lc1w5+l8'
           - DEBUG=1
           - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
           - POSTGRES_NAME=newdb
           - POSTGRES_USER=newuser
           - POSTGRES_PASSWORD='1'
       depends_on:
           - pg_db