version: '3.8'
services:
  pg_db:
      build: .
      image: postgres
      restart: always
      environment:
        - POSTGRES_PASSWORD='1'
        - POSTGRES_USER=newuser
        - POSTGRES_DB=newdb
      ports:
        - ${POSTGRES_PORT:-5433}:5432
  web:
       build: .
       depends_on:
           - pg_db
       command: python manage.py runserver 127.0.0.1:8000
       ports:
           - 8000:8000
       environment:
           - SECRET_KEY='django-insecure-pg+h99q6^$aksy$mtmdmz3)keh3t^+-r_lkta478^_lc1w5+l8'
           - DEBUG=1
           - DJANGO_ALLOWEDHOSTS=localhost 127.0.0.1 [::1]
