# Generated by Django 4.0.2 on 2022-02-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='departments',
        ),
        migrations.AddField(
            model_name='departments',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskapp.organizations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskapp.departments'),
            preserve_default=False,
        ),
    ]
