# Generated by Django 4.0.2 on 2022-02-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_departments_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskapp.organizations'),
        ),
    ]
